services:
  web:
    build: .
    container_name: tennis-table-web
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./static/img:/app/static/img
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - default
      - berlanggan_default

networks:
  berlanggan_default:
    external: true
