-- Normalized multi-sport core for InterSport tournaments.
-- IDs are generated by the application/importer so this migration needs no
-- database extension and remains compatible with managed PostgreSQL services.

CREATE SCHEMA IF NOT EXISTS intersport;

CREATE TABLE intersport.tournaments (
    id UUID PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    short_name TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'Asia/Jakarta',
    locale TEXT NOT NULL DEFAULT 'id-ID',
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'published', 'active', 'completed', 'cancelled')),
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    branding_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (ends_on >= starts_on)
);

CREATE TABLE intersport.sports (
    id UUID PRIMARY KEY,
    sport_key TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    icon TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE intersport.tournament_sports (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    sport_id UUID NOT NULL REFERENCES intersport.sports(id),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    feature_flags JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tournament_id, sport_id),
    UNIQUE (tournament_id, display_order)
);

CREATE TABLE intersport.rule_profiles (
    id UUID PRIMARY KEY,
    sport_id UUID NOT NULL REFERENCES intersport.sports(id),
    profile_key TEXT NOT NULL,
    version INTEGER NOT NULL CHECK (version > 0),
    name TEXT NOT NULL,
    segment_term TEXT NOT NULL,
    config JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (sport_id, profile_key, version)
);

CREATE TABLE intersport.standing_policies (
    id UUID PRIMARY KEY,
    policy_key TEXT NOT NULL,
    version INTEGER NOT NULL CHECK (version > 0),
    name TEXT NOT NULL,
    config JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (policy_key, version)
);

CREATE TABLE intersport.divisions (
    id UUID PRIMARY KEY,
    tournament_sport_id UUID NOT NULL REFERENCES intersport.tournament_sports(id) ON DELETE CASCADE,
    division_key TEXT NOT NULL,
    name TEXT NOT NULL,
    entrant_type TEXT NOT NULL CHECK (entrant_type IN ('individual', 'team')),
    min_team_size INTEGER NOT NULL DEFAULT 1 CHECK (min_team_size > 0),
    max_team_size INTEGER NOT NULL DEFAULT 1 CHECK (max_team_size >= min_team_size),
    default_rule_profile_id UUID NOT NULL REFERENCES intersport.rule_profiles(id),
    standing_policy_id UUID REFERENCES intersport.standing_policies(id),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tournament_sport_id, division_key)
);

CREATE TABLE intersport.people (
    id UUID PRIMARY KEY,
    display_name TEXT NOT NULL,
    employee_reference TEXT,
    privacy_flags JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE intersport.entrants (
    id UUID PRIMARY KEY,
    division_id UUID NOT NULL REFERENCES intersport.divisions(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    display_name TEXT NOT NULL,
    seed INTEGER CHECK (seed IS NULL OR seed > 0),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'withdrawn', 'disqualified')),
    branding JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (division_id, code)
);

CREATE TABLE intersport.entrant_members (
    id UUID PRIMARY KEY,
    entrant_id UUID NOT NULL REFERENCES intersport.entrants(id) ON DELETE CASCADE,
    person_id UUID NOT NULL REFERENCES intersport.people(id),
    member_role TEXT NOT NULL DEFAULT 'player',
    member_order INTEGER NOT NULL CHECK (member_order > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entrant_id, person_id),
    UNIQUE (entrant_id, member_order)
);

CREATE TABLE intersport.stages (
    id UUID PRIMARY KEY,
    division_id UUID NOT NULL REFERENCES intersport.divisions(id) ON DELETE CASCADE,
    stage_key TEXT NOT NULL,
    stage_type TEXT NOT NULL
        CHECK (stage_type IN ('round_robin', 'group', 'knockout', 'semifinal', 'final', 'classification')),
    name TEXT NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    qualification_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (division_id, stage_key),
    UNIQUE (division_id, sequence)
);

CREATE TABLE intersport.groups (
    id UUID PRIMARY KEY,
    stage_id UUID NOT NULL REFERENCES intersport.stages(id) ON DELETE CASCADE,
    group_key TEXT NOT NULL,
    name TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (stage_id, group_key)
);

CREATE TABLE intersport.venues (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    address TEXT,
    timezone TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tournament_id, name)
);

CREATE TABLE intersport.courts (
    id UUID PRIMARY KEY,
    venue_id UUID NOT NULL REFERENCES intersport.venues(id) ON DELETE CASCADE,
    sport_id UUID NOT NULL REFERENCES intersport.sports(id),
    court_key TEXT NOT NULL,
    name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (venue_id, sport_id, court_key)
);

CREATE TABLE intersport.matches (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    division_id UUID NOT NULL REFERENCES intersport.divisions(id),
    stage_id UUID NOT NULL REFERENCES intersport.stages(id),
    group_id UUID REFERENCES intersport.groups(id),
    display_code TEXT NOT NULL,
    round_number INTEGER,
    round_label TEXT,
    entrant_a_id UUID REFERENCES intersport.entrants(id),
    entrant_b_id UUID REFERENCES intersport.entrants(id),
    court_id UUID REFERENCES intersport.courts(id),
    rule_profile_id UUID NOT NULL REFERENCES intersport.rule_profiles(id),
    scheduled_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'scheduled', 'check_in', 'live', 'postponed', 'suspended', 'cancelled', 'completed')),
    result_type TEXT NOT NULL DEFAULT 'normal'
        CHECK (result_type IN ('normal', 'walkover', 'cancelled')),
    winner_entrant_id UUID REFERENCES intersport.entrants(id),
    result_valid BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    notes TEXT NOT NULL DEFAULT '',
    source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tournament_id, display_code),
    CHECK (entrant_a_id IS NULL OR entrant_b_id IS NULL OR entrant_a_id <> entrant_b_id),
    CHECK (winner_entrant_id IS NULL OR winner_entrant_id IN (entrant_a_id, entrant_b_id)),
    CHECK (status <> 'completed' OR winner_entrant_id IS NOT NULL OR result_type = 'cancelled'),
    CHECK (status <> 'completed' OR result_valid)
);

CREATE TABLE intersport.match_segments (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES intersport.matches(id) ON DELETE CASCADE,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    segment_type TEXT NOT NULL,
    score_a INTEGER NOT NULL CHECK (score_a >= 0),
    score_b INTEGER NOT NULL CHECK (score_b >= 0),
    status TEXT NOT NULL DEFAULT 'completed'
        CHECK (status IN ('pending', 'in_progress', 'completed', 'invalid')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (match_id, sequence)
);

CREATE TABLE intersport.score_events (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES intersport.matches(id) ON DELETE CASCADE,
    sequence BIGINT NOT NULL CHECK (sequence > 0),
    event_type TEXT NOT NULL,
    side TEXT CHECK (side IN ('a', 'b')),
    value INTEGER,
    actor_user_id UUID,
    idempotency_key TEXT NOT NULL,
    reversal_of_id UUID REFERENCES intersport.score_events(id),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (match_id, sequence),
    UNIQUE (match_id, idempotency_key)
);

CREATE TABLE intersport.stream_sessions (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    match_id UUID REFERENCES intersport.matches(id) ON DELETE SET NULL,
    court_id UUID REFERENCES intersport.courts(id) ON DELETE SET NULL,
    provider TEXT NOT NULL,
    provider_reference TEXT,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'scheduled', 'ready', 'live', 'ended', 'failed', 'cancelled')),
    privacy TEXT NOT NULL DEFAULT 'unlisted'
        CHECK (privacy IN ('public', 'unlisted', 'authenticated')),
    scheduled_start TIMESTAMPTZ,
    playback_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (match_id IS NOT NULL OR court_id IS NOT NULL)
);

CREATE TABLE intersport.media_assets (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    owner_type TEXT NOT NULL,
    owner_id UUID,
    storage_key TEXT,
    source_url TEXT,
    mime_type TEXT,
    width INTEGER CHECK (width IS NULL OR width > 0),
    height INTEGER CHECK (height IS NULL OR height > 0),
    moderation_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (moderation_status IN ('pending', 'approved', 'hidden', 'deleted')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (storage_key IS NOT NULL OR source_url IS NOT NULL)
);

CREATE TABLE intersport.announcements (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    sport_id UUID REFERENCES intersport.sports(id),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'published', 'expired', 'cancelled')),
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at)
);

CREATE TABLE intersport.comments (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES intersport.matches(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    body TEXT NOT NULL,
    moderation_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (moderation_status IN ('pending', 'approved', 'hidden', 'deleted')),
    source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE intersport.reactions (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES intersport.matches(id) ON DELETE CASCADE,
    side TEXT NOT NULL CHECK (side IN ('a', 'b')),
    reaction TEXT NOT NULL,
    actor_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (match_id, actor_hash, reaction)
);

-- Legacy votes were stored only as aggregate counts, so they cannot be
-- truthfully expanded into individual actor records during migration.
CREATE TABLE intersport.legacy_reaction_totals (
    id UUID PRIMARY KEY,
    match_id UUID NOT NULL REFERENCES intersport.matches(id) ON DELETE CASCADE,
    side TEXT NOT NULL CHECK (side IN ('a', 'b')),
    reaction TEXT NOT NULL,
    reaction_count INTEGER NOT NULL CHECK (reaction_count >= 0),
    UNIQUE (match_id, side, reaction)
);

CREATE TABLE intersport.users (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    password_hash TEXT,
    sso_subject TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled', 'locked')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (password_hash IS NOT NULL OR sso_subject IS NOT NULL)
);

CREATE TABLE intersport.roles (
    id UUID PRIMARY KEY,
    role_key TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    permissions JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE intersport.user_roles (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES intersport.users(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES intersport.roles(id) ON DELETE CASCADE,
    tournament_id UUID REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    sport_id UUID REFERENCES intersport.sports(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, role_id, tournament_id, sport_id)
);

ALTER TABLE intersport.score_events
    ADD CONSTRAINT score_events_actor_user_fk
    FOREIGN KEY (actor_user_id) REFERENCES intersport.users(id) ON DELETE SET NULL;

CREATE TABLE intersport.audit_logs (
    id UUID PRIMARY KEY,
    tournament_id UUID REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    actor_user_id UUID REFERENCES intersport.users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id UUID,
    before_data JSONB,
    after_data JSONB,
    reason TEXT,
    request_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE intersport.import_runs (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL REFERENCES intersport.tournaments(id) ON DELETE CASCADE,
    source_kind TEXT NOT NULL,
    source_checksums JSONB NOT NULL,
    report JSONB NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tournament_id, source_kind, source_checksums)
);

CREATE FUNCTION intersport.prevent_rule_profile_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF ROW(OLD.sport_id, OLD.profile_key, OLD.version, OLD.config)
       IS DISTINCT FROM
       ROW(NEW.sport_id, NEW.profile_key, NEW.version, NEW.config) THEN
        RAISE EXCEPTION 'Rule profiles are immutable; create a new version instead';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER rule_profiles_immutable
BEFORE UPDATE ON intersport.rule_profiles
FOR EACH ROW EXECUTE FUNCTION intersport.prevent_rule_profile_mutation();

CREATE FUNCTION intersport.prevent_standing_policy_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF ROW(OLD.policy_key, OLD.version, OLD.config)
       IS DISTINCT FROM
       ROW(NEW.policy_key, NEW.version, NEW.config) THEN
        RAISE EXCEPTION 'Standing policies are immutable; create a new version instead';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER standing_policies_immutable
BEFORE UPDATE ON intersport.standing_policies
FOR EACH ROW EXECUTE FUNCTION intersport.prevent_standing_policy_mutation();

CREATE INDEX matches_schedule_idx
    ON intersport.matches (tournament_id, scheduled_at, status);
CREATE INDEX matches_division_stage_idx
    ON intersport.matches (division_id, stage_id, group_id);
CREATE INDEX comments_moderation_idx
    ON intersport.comments (moderation_status, created_at);
CREATE INDEX streams_live_idx
    ON intersport.stream_sessions (tournament_id, status, scheduled_start);
CREATE INDEX audit_entity_idx
    ON intersport.audit_logs (entity_type, entity_id, created_at);

-- A court cannot host two published/active matches at the exact same time.
CREATE UNIQUE INDEX matches_active_court_time_unique
    ON intersport.matches (court_id, scheduled_at)
    WHERE court_id IS NOT NULL
      AND scheduled_at IS NOT NULL
      AND status IN ('scheduled', 'check_in', 'live');
